// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'folder': string;
  'folderName': string;
  'folderPath': string;
  'format': string;
  'formatContainer': string;
  'formatInput': string;
  'formats': string;
  'formatsCell': string;
  'input': string;
  'series': string;
}
export const cssExports: CssExports;
export default cssExports;
