// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'error': string;
  'footer': string;
  'inputContainer': string;
  'inputs': string;
  'label': string;
  'notImportedFolders': string;
  'searchContainer': string;
  'searchInput': string;
  'searchLabelContainer': string;
  'success': string;
}
export const cssExports: CssExports;
export default cssExports;
