// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'freeSpace': string;
  'helpText': string;
  'message': string;
  'path': string;
  'row': string;
  'suggestedRow': string;
  'unmappedFolders': string;
}
export const cssExports: CssExports;
export default cssExports;
