// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'caret': string;
  'currentResult': string;
  'existing': string;
  'loading': string;
  'message': string;
  'noMatch': string;
  'result': string;
  'searchInput': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
