// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'caption': string;
  'card': string;
  'code': string;
  'container': string;
  'kaomoji': string;
  'message': string;
}
export const cssExports: CssExports;
export default cssExports;
