// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blockedRow': string;
  'previews': string;
  'row': string;
  'series': string;
}
export const cssExports: CssExports;
export default cssExports;
