// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionMenuIcon': string;
  'actions': string;
  'actionsMenu': string;
  'actionsMenuContent': string;
  'bookCount': string;
  'bookType': string;
  'bookTypeLabel': string;
  'books': string;
  'collapseButtonContainer': string;
  'collapseButtonIcon': string;
  'episodeCountTooltip': string;
  'expandButton': string;
  'expandButtonIcon': string;
  'header': string;
  'left': string;
  'mediaTypeCount': string;
  'mediaTypeHeader': string;
  'mediaTypeTabs': string;
  'mediaTypeTitle': string;
  'noBooks': string;
  'tabCount': string;
  'tabDownloading': string;
  'volumeCount': string;
}
export const cssExports: CssExports;
export default cssExports;
