// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blocked': string;
  'heading': string;
  'hint': string;
  'line': string;
  'lineFacts': string;
  'lineName': string;
  'lineText': string;
  'switchLine': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
