// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alreadyExistsIcon': string;
  'aniListLink': string;
  'aniListLinkIcon': string;
  'content': string;
  'icons': string;
  'lineFacts': string;
  'name': string;
  'nameContainer': string;
  'nameRow': string;
  'overlay': string;
  'overview': string;
  'poster': string;
  'searchResult': string;
  'titleRow': string;
  'underlay': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
