using System.Collections.Generic;
using System.Text;
using FluentAssertions;
using NUnit.Framework;
using NzbDrone.Core.MediaFiles.PdfConversion;
using NzbDrone.Core.Test.Framework;

namespace NzbDrone.Core.Test.MediaFiles.PdfConversion
{
    [TestFixture]
    public class PgmBrightnessFixture : CoreTest
    {
        private static byte[] Pgm(int width, int height, int maxval, byte[] pixels)
        {
            var header = Encoding.ASCII.GetBytes($"P5\n{width} {height}\n{maxval}\n");
            var bytes = new List<byte>(header);
            bytes.AddRange(pixels);
            return bytes.ToArray();
        }

        [Test]
        public void white_page_is_near_one()
        {
            var pixels = new byte[] { 255, 255, 255, 255 };
            PopplerPdfImageExtractor.MeanBrightness(Pgm(2, 2, 255, pixels)).Should().BeApproximately(1.0, 0.001);
        }

        [Test]
        public void black_page_is_zero()
        {
            var pixels = new byte[] { 0, 0, 0, 0 };
            PopplerPdfImageExtractor.MeanBrightness(Pgm(2, 2, 255, pixels)).Should().BeApproximately(0.0, 0.001);
        }

        [Test]
        public void mid_gray_is_about_half()
        {
            var pixels = new byte[] { 128, 128, 128, 128 };
            PopplerPdfImageExtractor.MeanBrightness(Pgm(2, 2, 255, pixels)).Should().BeApproximately(0.502, 0.01);
        }

        [Test]
        public void handles_a_comment_line_in_the_header()
        {
            var header = Encoding.ASCII.GetBytes("P5\n# generated by pdftoppm\n2 1\n255\n");
            var bytes = new List<byte>(header) { 255, 0 };
            PopplerPdfImageExtractor.MeanBrightness(bytes.ToArray()).Should().BeApproximately(0.5, 0.01);
        }
    }
}
