// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'container': string;
  'lines': string;
  'list': string;
  'name': string;
  'otherSeries': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
