// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'caption': string;
  'card': string;
  'container': string;
  'details': string;
  'imageContainer': string;
  'kaomoji': string;
  'message': string;
  'version': string;
}
export const cssExports: CssExports;
export default cssExports;
