// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'name': string;
  'summary': string;
}
export const cssExports: CssExports;
export default cssExports;
