// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'addButton': string;
  'card': string;
  'collection': string;
  'counts': string;
  'header': string;
  'members': string;
  'missing': string;
  'name': string;
  'poster': string;
  'posterLink': string;
  'root': string;
  'sub': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
